### ISSUE TITLE
Hero component clipping letters

### ISSUE THREAD

**Issue by NikhilBehari** [pxblue/component-library#10]
Hero component is clipping lowercase letters (g, p, q) at the bottom

**Comment by NikhilBehari** [comment]
React and Angular

**Comment by joebochill** [comment]
This can be fixed by setting lineHeight to 1.2 for the label and the channel value pieces, and reducing the bottom margin on the hero icon to ~5px instead of 10.

**Comment by joebochill** [comment]
Can be verified in @pxblue/angular-components@1.1.1 and @pxblue/react-components@1.0.1
