### ISSUE TITLE
Drawer Components Should look good in dark theme

### ISSUE THREAD

**Issue by joebochill** [pxblue/component-library#103]
#### Describe the desired behavior
Drawer should look proper when used in the PX Blue dark theme.

#### Describe the current behavior
Looks a little janky.

#### Additional Context
![image](https://user-images.githubusercontent.com/29152776/73876921-d7384380-4825-11ea-9a08-b86585f4259b.png)
should look more like:
![image](https://user-images.githubusercontent.com/29152776/73952907-9d227c80-48cd-11ea-9034-deb232cda360.png)

**Comment by huayunh** [comment]
To eliminate potential wheel reinvention, I made a branch here: 
https://github.com/pxblue/component-library/tree/bug/react-drawer-in-dark

Still requires some tweaking on the activeRoute, but everything else should be fine
(Oh, and we will also need an Eaton logo on dark background)
