### ISSUE TITLE
InfoListItem should support third line of text

### ISSUE THREAD

**Issue by joebochill** [pxblue/component-library#62]
#### Describe the desired behavior
Material Design Lists support up to three lines of text in list items

#### Describe the current behavior
InfoListItem only allows configuration for title and subtitle (2 lines)

#### Is this request related to a current issue?
No

#### Additional Context
This will need to be updated for the React and React Native libraries. Ask Eric for style input.

**Comment by emclaug2** [comment]
Migrated here (reactnative): https://github.com/pxblue/react-native-component-library/issues/4
Migrated here (react): https://github.com/pxblue/react-component-library/issues/3
