### ISSUE TITLE
Headers does not match each other in the styling

### ISSUE THREAD

**Issue by huayunh** [pxblue/component-library#74]
#### Describe the bug
The `<Header />` component renders differently across different branches.

#### What is the expected behavior?
Their title should all be left-aligned and bolded, and the application bar should have the same height for different sized view port unless specified otherwise.

#### What are the steps to reproduce?
1. goto our multiselect-list and status-list repo
2. open the code examples in online editors
3. compare the rendered result for each branch side-by-side

#### Screenshots or links to minimum reproduction example
multiselect-list
![image](https://user-images.githubusercontent.com/8997218/72071767-90a10900-32ba-11ea-9b85-e5b815d75977.png)

Status-list
![image](https://user-images.githubusercontent.com/8997218/72071932-e5448400-32ba-11ea-9096-7311761d0b16.png)

#### What is your environment?

 Framework
- [x] Angular
- [x] React
- [x] React Native

 Browser
- [ ] Internet Explorer
- [ ] Edge
- [ ] Safari
- [x] Chrome
- [ ] Firefox

 Operating System
- [x] MacOS
- [ ] Windows
- [ ] Other

**Comment by joebochill** [comment]
@huayunh can we move this to JIRA? We don't have header components for Angular, React, or Ionic, so this is more of an implementation issue in the code examples themselves rather than the component library.

**Comment by huayunh** [comment]
> @huayunh can we move this to JIRA?

I already created a story and referred this one and [multiselect-list#39](https://github.com/pxblue/multiselect-list/issues/39). I personally prefer this way: bug report for the repos with things not matching each other, and link them in jira.

**Comment by joebochill** [comment]
Yeah that's fine, I just don't believe this is the right repo for this bug since none of the examples are using Header components from this library.

**Comment by emclaug2** [comment]
Migrated here: https://github.com/pxblue/multiselect-list/issues/40
