### ISSUE TITLE
Drawer Should support nested/expandable items

### ISSUE THREAD

**Issue by joebochill** [pxblue/component-library#87]
#### Describe the desired behavior
The NavGroup should be able to support nested content, similar to how this is used on our documentation site.

#### Describe the current behavior
Only supports flat list.

#### Is this request related to a current issue?
Not yet, but it will be required for the documentation site overhaul and also likely in WAS.

**Comment by emclaug2** [comment]
Duplicate of  https://github.com/pxblue/react-component-library/issues/5
